### PR TITLE
Create install.bat

### PR DESCRIPTION
**Pull request by derNiklaas**
kinda ugly... but it works... 🤔

### CODE REVIEW

**Comment by derNiklaas** [comment]
That batch file doesn't work atm.

It will check if git, sbt, yarn and npm are installed.
It can download the 4 repos and perform sbt tasks

there is still an error trying to installing the GUI: 

> npm WARN @ngtools/webpack@6.0.5 requires a peer of typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN chatoverflow-api@0.2.5 requires a peer of zone.js@^0.7.6 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.3.0 requires a peer of @angular/compiler@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.3.0 requires a peer of @angular/core@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-html@0.23.7 requires a peer of postcss-syntax@^0.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-markdown@0.23.7 requires a peer of postcss-syntax@^0.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-microsoft-contrib@5.0.3 requires a peer of typescript@^2.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by strifel** [comment]
@derNiklaas Isn't that just a warning?

**Comment by derNiklaas** [comment]
@strifel Yes, just noticed that....

**Comment by derNiklaas** [comment]
Tested that batch file. 
Works on my machine.

Can anyone else verify that?

**Comment by J0B10** [comment]
Tested on two PCs, once with dependencys installed and once without. Worked as intended both times!

**Pull request merged**
