### PR TITLE
Fix dev checkout after build

### PR DESCRIPTION
**Pull request by molikuner**
This is necessary because sometimes for example the `package-lock.json` for the GUI is changed by the build. With this change, the local changes of the build are ignored and overwritten by origin.

```bash
$ ./install.sh --dev                                                                                                                                                                                                                         
 * Testing for dependencies...                                                                                                                                                                                                                
 * Cloning repositories...                                                                                                                                                                                                                    
Cloning into 'chatoverflow'...                                                                                                                                                                                                                
remote: Enumerating objects: 64, done.                                                                                                                                                                                                        
remote: Counting objects: 100% (64/64), done.                                                                                                                                                                                                 
remote: Compressing objects: 100% (34/34), done.                                                                                                                                                                                              
remote: Total 7104 (delta 26), reused 52 (delta 15), pack-reused 7040                                                                                                                                                                         
Receiving objects: 100% (7104/7104), 1.46 MiB | 2.67 MiB/s, done.                                                                                                                                                                             
Resolving deltas: 100% (2998/2998), done.                                                                                                                                                                                                     
Cloning into 'chatoverflow/api'...                                                                                                                                                                                                            
remote: Enumerating objects: 421, done.                                                                                                                                                                                                       
remote: Counting objects: 100% (421/421), done.                                                                                                                                                                                               
remote: Compressing objects: 100% (162/162), done.                                                                                                                                                                                            
remote: Total 2257 (delta 175), reused 338 (delta 109), pack-reused 1836                                                                                                                                                                      
Receiving objects: 100% (2257/2257), 247.64 KiB | 960.00 KiB/s, done.                                                                                                                                                                         
Resolving deltas: 100% (877/877), done.                                                                                                                                                                                                       
Cloning into 'chatoverflow/gui'...                                                                                                                                                                                                            
remote: Enumerating objects: 81, done.                                                                                                                                                                                                        
remote: Counting objects: 100% (81/81), done.                                                                                                                                                                                                 
remote: Compressing objects: 100% (57/57), done.                                                                                                                                                                                              
remote: Total 525 (delta 43), reused 54 (delta 24), pack-reused 444                                                                                                                                                                           
Receiving objects: 100% (525/525), 613.68 KiB | 243.00 KiB/s, done.                                                                                                                                                                           
Resolving deltas: 100% (211/211), done.                                                                                                                                                                                                       
Cloning into 'chatoverflow/plugins-public'...                                                                                                                                                                                                 
remote: Enumerating objects: 192, done.                                                                                                                                                                                                       
remote: Counting objects: 100% (192/192), done.                                                                                                                                                                                               
remote: Compressing objects: 100% (84/84), done.                                                                                                                                                                                              
remote: Total 744 (delta 47), reused 162 (delta 31), pack-reused 552                                                                                                                                                                          
Receiving objects: 100% (744/744), 84.71 KiB | 652.00 KiB/s, done.                                                                                                                                                                            
Resolving deltas: 100% (205/205), done.                                                                                                                                                                                                       
 * Refreshing using sbt...                                                                                                                                                                                                                    
[info] Loading settings from assembly.sbt,plugins.sbt ...                                                                                                                                                                                     


...

added 1312 packages from 931 contributors and audited 35617 packages in 26.084s                                                                                                                                                               
found 487 vulnerabilities (2 low, 1 moderate, 484 high)                                                                                                                                                                                       
  run `npm audit fix` to fix them, or `npm audit` for details                                                                                                                                                                                 
* Switching to develop  branch                                                                                                                                                                                                                
Branch 'develop' set up to track remote branch 'develop' from 'origin'.                                                                                                                                                                       
Switched to a new branch 'develop'                                                                                                                                                                                                            
Branch 'develop' set up to track remote branch 'develop' from 'origin'.                                                                                                                                                                       
Switched to a new branch 'develop'                                                                                                                                                                                                            
error: Your local changes to the following files would be overwritten by checkout:                                                                                                                                                            
        package-lock.json                                                                                                                                                                                                                     
Please commit your changes or stash them before you switch branches.                                                                                                                                                                          
Aborting                                                                                                                                                                                                                                      
Branch 'develop' set up to track remote branch 'develop' from 'origin'.                                                                                                                                                                       
Switched to a new branch 'develop'
 * Success! You can now open the project in IntelliJ (or whatever IDE you prefer)
```

### CODE REVIEW

**Comment by molikuner** [comment]
Just to understand why it is like that. Why does the script build first and then attempts to change the branch? This type of error would be avoided by first changing the branch and then building afterwards. It would also have the advantage that all changes would be used in the (first) build without specifying the `--build` flag.

**Comment by J0B10** [comment]
Yes you are absolutely right about that.  
It would make way more sense to checkout the dev branch directly after cloning.

I think we got this wrong cause we added the dev option later cause we assumed the user might want to checkout dev after finishing the installation so we added it to the end of the script, not thinking ablut where the best place would be.

**Comment by J0B10** [comment]
Do you want to update your pull request so it checks out the dev branch at the right time? 

Sorry for any typos, send this from mobile phone :see_no_evil:

**Comment by hlxid** [comment]
:+1: Thanks for this Pull Request!

**Pull request merged**
