### PR TITLE
[*nix] Add initial version of script

### PR DESCRIPTION
**Pull request by justgerd**
This is the initial version of the *nix (linux/darwin/similar unixes) install script

### CODE REVIEW

**Comment by sebinside** [comment]
Any updates?

**Comment by justgerd** [comment]
unix script is now working, doesn't have a hard sbt dependency anymore, and is tested on linux (arch linux) and macos (catalina, with a quite non-standard $PATH). should theoretically work on every unix system with bash. Maybe even windows via gitbash, but that's untested.

**Comment by justgerd** [comment]
oh yeah, the one-liner that can be used for testing is `bash <(curl -s https://raw.githubusercontent.com/gerd2002/chatoverflow-setup/feature/unix-script/install.sh)`

Final oneliner would probably be something along the lines of `bash <(curl -sL https:/codeoverflow.org/install)` where install redirects to the raw.githubusercontent.com url of the script

**Comment by sebinside** [comment]
Tested, worked fine, thanks a lot!

Next up / Ideas: `--dev` option, `bat` file for native windows support

**Pull request merged**
